@startuml TrackingDiagram
left to right direction
skinparam shadowing false

actor "Customer" as Customer
actor "Delivery Personnel" as Shipper

rectangle "Real-time Tracking" {

  usecase "Track Order Status\nin Real Time" as UC_TRACK_01

  usecase "View Live GPS of\nShipper on Map" as UC_TRACK_02

  usecase "Share Live\nDelivery Location" as UC_TRACK_03

  usecase "View Estimated\nArrival Time" as UC_TRACK_04
}

Customer --> UC_TRACK_01
Customer --> UC_TRACK_02
Customer --> UC_TRACK_04

Shipper --> UC_TRACK_03

UC_TRACK_02 ..> UC_TRACK_03 : <<include>>

@enduml