extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  basicauth/grafana_cloud:
    client_auth:
      username: ${env:GRAFANA_CLOUD_OTLP_USERNAME_OR_INSTANCE_ID}
      password: ${env:GRAFANA_CLOUD_OTLP_TOKEN}

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64
  batch:
    timeout: 5s
    send_batch_size: 512
  resource:
    attributes:
      - key: collector.name
        value: uitfood-otel-collector
        action: upsert

exporters:
  debug:
    verbosity: basic
  otlphttp/grafana_cloud:
    endpoint: ${env:GRAFANA_CLOUD_OTLP_ENDPOINT}
    auth:
      authenticator: basicauth/grafana_cloud
    compression: gzip

service:
  extensions: [health_check, basicauth/grafana_cloud]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, otlphttp/grafana_cloud]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, otlphttp/grafana_cloud]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, otlphttp/grafana_cloud]
