name: CI/CD Pipeline

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    secrets: inherit

  publish-api-docker:
    name: Publish API Docker Image
    needs: validate
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish-docker.yml
    with:
      app: api
      gh_actor: ${{ github.actor }}
      gh_repository: ${{ github.repository }}
    secrets: inherit

  publish-web-docker:
    name: Publish Web Docker Image
    needs: validate
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish-docker.yml
    with:
      app: web
      gh_actor: ${{ github.actor }}
      gh_repository: ${{ github.repository }}
    secrets: inherit

  publish-mobile:
    needs: validate
    uses: ./.github/workflows/publish-mobile.yml
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
