name: Publish Docker

on:
  workflow_call:
    inputs:
      gh_actor:
        required: true
        type: string
      gh_repository:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Package & Publish Docker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [api, web]
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Log in to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ inputs.gh_actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ghcr.io/${{ inputs.gh_repository }}-${{ matrix.app }}
          tags: |
            type=ref,event=branch
            type=sha,format=short

      - name: Build & Push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          file: apps/${{ matrix.app }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.app }}
          cache-to: type=gha,mode=max,scope=${{ matrix.app }}