name: Publish Mobile

on:
  workflow_call:
    secrets:
      EXPO_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  publish-mobile:
    name: Package Mobile (EAS)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Setup Expo
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Package (EAS Build Production)
        working-directory: apps/mobile
        run: eas build --platform android --profile production --non-interactive --no-wait